/** Generated by the sketch-fonts plugin in vite.config.ts from the pinned @excalidraw/excalidraw. */
declare module "virtual:sketch-fonts" {
  const faces: { family: string; url: string; unicodeRange: string; weight?: string }[];
  export default faces;
}
