/** Generated by the excalifont plugin in vite.config.ts from the pinned @excalidraw/excalidraw. */
declare module "virtual:excalifont" {
  const faces: { url: string; unicodeRange: string }[];
  export default faces;
}
